spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false


  datasource:
    url: jdbc:mysql://localhost:3306/SECURITY_db
    username: root
    password: root

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080